// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	booking "github.com/internships-backend/test-backend-M0s1ck/internal/domain/booking"
)

// MockbookingRepo is a mock of bookingRepo interface.
type MockbookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepoMockRecorder
}

// MockbookingRepoMockRecorder is the mock recorder for MockbookingRepo.
type MockbookingRepoMockRecorder struct {
	mock *MockbookingRepo
}

// NewMockbookingRepo creates a new mock instance.
func NewMockbookingRepo(ctrl *gomock.Controller) *MockbookingRepo {
	mock := &MockbookingRepo{ctrl: ctrl}
	mock.recorder = &MockbookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepo) EXPECT() *MockbookingRepoMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockbookingRepo) Cancel(ctx context.Context, id uuid.UUID, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockbookingRepoMockRecorder) Cancel(ctx, id, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockbookingRepo)(nil).Cancel), ctx, id, now)
}

// GetByID mocks base method.
func (m *MockbookingRepo) GetByID(ctx context.Context, id uuid.UUID) (*booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockbookingRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockbookingRepo)(nil).GetByID), ctx, id)
}
