// Code generated by MockGen. DO NOT EDIT.
// Source: ensure_room_on_date_filled.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ensureroomdate "github.com/internships-backend/test-backend-M0s1ck/internal/usecase/slot/ensureroomdate"
)

// MockensureRoomOnDateFilledUsecase is a mock of ensureRoomOnDateFilledUsecase interface.
type MockensureRoomOnDateFilledUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockensureRoomOnDateFilledUsecaseMockRecorder
}

// MockensureRoomOnDateFilledUsecaseMockRecorder is the mock recorder for MockensureRoomOnDateFilledUsecase.
type MockensureRoomOnDateFilledUsecaseMockRecorder struct {
	mock *MockensureRoomOnDateFilledUsecase
}

// NewMockensureRoomOnDateFilledUsecase creates a new mock instance.
func NewMockensureRoomOnDateFilledUsecase(ctrl *gomock.Controller) *MockensureRoomOnDateFilledUsecase {
	mock := &MockensureRoomOnDateFilledUsecase{ctrl: ctrl}
	mock.recorder = &MockensureRoomOnDateFilledUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockensureRoomOnDateFilledUsecase) EXPECT() *MockensureRoomOnDateFilledUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockensureRoomOnDateFilledUsecase) Execute(ctx context.Context, req *ensureroomdate.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockensureRoomOnDateFilledUsecaseMockRecorder) Execute(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockensureRoomOnDateFilledUsecase)(nil).Execute), ctx, req)
}
