// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	booking "github.com/internships-backend/test-backend-M0s1ck/internal/domain/booking"
)

// MockbookingRepo is a mock of bookingRepo interface.
type MockbookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepoMockRecorder
}

// MockbookingRepoMockRecorder is the mock recorder for MockbookingRepo.
type MockbookingRepoMockRecorder struct {
	mock *MockbookingRepo
}

// NewMockbookingRepo creates a new mock instance.
func NewMockbookingRepo(ctrl *gomock.Controller) *MockbookingRepo {
	mock := &MockbookingRepo{ctrl: ctrl}
	mock.recorder = &MockbookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepo) EXPECT() *MockbookingRepoMockRecorder {
	return m.recorder
}

// ListFutureActiveByUser mocks base method.
func (m *MockbookingRepo) ListFutureActiveByUser(ctx context.Context, userID uuid.UUID, now time.Time) ([]booking.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFutureActiveByUser", ctx, userID, now)
	ret0, _ := ret[0].([]booking.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFutureActiveByUser indicates an expected call of ListFutureActiveByUser.
func (mr *MockbookingRepoMockRecorder) ListFutureActiveByUser(ctx, userID, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFutureActiveByUser", reflect.TypeOf((*MockbookingRepo)(nil).ListFutureActiveByUser), ctx, userID, now)
}
