// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	booking "github.com/internships-backend/test-backend-M0s1ck/internal/domain/booking"
)

// MockbookingRepo is a mock of bookingRepo interface.
type MockbookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepoMockRecorder
}

// MockbookingRepoMockRecorder is the mock recorder for MockbookingRepo.
type MockbookingRepoMockRecorder struct {
	mock *MockbookingRepo
}

// NewMockbookingRepo creates a new mock instance.
func NewMockbookingRepo(ctrl *gomock.Controller) *MockbookingRepo {
	mock := &MockbookingRepo{ctrl: ctrl}
	mock.recorder = &MockbookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepo) EXPECT() *MockbookingRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockbookingRepo) List(ctx context.Context, page, pageSize int) ([]booking.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].([]booking.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockbookingRepoMockRecorder) List(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockbookingRepo)(nil).List), ctx, page, pageSize)
}
