// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	room "github.com/internships-backend/test-backend-M0s1ck/internal/domain/room"
)

// MockroomRepo is a mock of roomRepo interface.
type MockroomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepoMockRecorder
}

// MockroomRepoMockRecorder is the mock recorder for MockroomRepo.
type MockroomRepoMockRecorder struct {
	mock *MockroomRepo
}

// NewMockroomRepo creates a new mock instance.
func NewMockroomRepo(ctrl *gomock.Controller) *MockroomRepo {
	mock := &MockroomRepo{ctrl: ctrl}
	mock.recorder = &MockroomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepo) EXPECT() *MockroomRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockroomRepo) List(ctx context.Context) ([]*room.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*room.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockroomRepoMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockroomRepo)(nil).List), ctx)
}
