// Code generated by MockGen. DO NOT EDIT.
// Source: conf_link_provider.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockconferenceLinkProvider is a mock of conferenceLinkProvider interface.
type MockconferenceLinkProvider struct {
	ctrl     *gomock.Controller
	recorder *MockconferenceLinkProviderMockRecorder
}

// MockconferenceLinkProviderMockRecorder is the mock recorder for MockconferenceLinkProvider.
type MockconferenceLinkProviderMockRecorder struct {
	mock *MockconferenceLinkProvider
}

// NewMockconferenceLinkProvider creates a new mock instance.
func NewMockconferenceLinkProvider(ctrl *gomock.Controller) *MockconferenceLinkProvider {
	mock := &MockconferenceLinkProvider{ctrl: ctrl}
	mock.recorder = &MockconferenceLinkProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconferenceLinkProvider) EXPECT() *MockconferenceLinkProviderMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockconferenceLinkProvider) CreateLink(ctx context.Context, slotID, userID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, slotID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockconferenceLinkProviderMockRecorder) CreateLink(ctx, slotID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockconferenceLinkProvider)(nil).CreateLink), ctx, slotID, userID)
}
