// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	booking "github.com/internships-backend/test-backend-M0s1ck/internal/domain/booking"
	slot "github.com/internships-backend/test-backend-M0s1ck/internal/domain/slot"
)

// MockbookingRepo is a mock of bookingRepo interface.
type MockbookingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockbookingRepoMockRecorder
}

// MockbookingRepoMockRecorder is the mock recorder for MockbookingRepo.
type MockbookingRepoMockRecorder struct {
	mock *MockbookingRepo
}

// NewMockbookingRepo creates a new mock instance.
func NewMockbookingRepo(ctrl *gomock.Controller) *MockbookingRepo {
	mock := &MockbookingRepo{ctrl: ctrl}
	mock.recorder = &MockbookingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbookingRepo) EXPECT() *MockbookingRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockbookingRepo) Create(ctx context.Context, booking *booking.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockbookingRepoMockRecorder) Create(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockbookingRepo)(nil).Create), ctx, booking)
}

// MockslotRepo is a mock of slotRepo interface.
type MockslotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepoMockRecorder
}

// MockslotRepoMockRecorder is the mock recorder for MockslotRepo.
type MockslotRepoMockRecorder struct {
	mock *MockslotRepo
}

// NewMockslotRepo creates a new mock instance.
func NewMockslotRepo(ctrl *gomock.Controller) *MockslotRepo {
	mock := &MockslotRepo{ctrl: ctrl}
	mock.recorder = &MockslotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepo) EXPECT() *MockslotRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockslotRepo) GetByID(ctx context.Context, slotID uuid.UUID) (*slot.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, slotID)
	ret0, _ := ret[0].(*slot.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockslotRepoMockRecorder) GetByID(ctx, slotID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockslotRepo)(nil).GetByID), ctx, slotID)
}
