// Code generated by MockGen. DO NOT EDIT.
// Source: hasher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockpassHasher is a mock of passHasher interface.
type MockpassHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpassHasherMockRecorder
}

// MockpassHasherMockRecorder is the mock recorder for MockpassHasher.
type MockpassHasherMockRecorder struct {
	mock *MockpassHasher
}

// NewMockpassHasher creates a new mock instance.
func NewMockpassHasher(ctrl *gomock.Controller) *MockpassHasher {
	mock := &MockpassHasher{ctrl: ctrl}
	mock.recorder = &MockpassHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpassHasher) EXPECT() *MockpassHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockpassHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpassHasherMockRecorder) Hash(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpassHasher)(nil).Hash), password)
}
