// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	slot "github.com/internships-backend/test-backend-M0s1ck/internal/domain/slot"
)

// MockroomRepo is a mock of roomRepo interface.
type MockroomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepoMockRecorder
}

// MockroomRepoMockRecorder is the mock recorder for MockroomRepo.
type MockroomRepoMockRecorder struct {
	mock *MockroomRepo
}

// NewMockroomRepo creates a new mock instance.
func NewMockroomRepo(ctrl *gomock.Controller) *MockroomRepo {
	mock := &MockroomRepo{ctrl: ctrl}
	mock.recorder = &MockroomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepo) EXPECT() *MockroomRepoMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockroomRepo) Exists(ctx context.Context, roomID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockroomRepoMockRecorder) Exists(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockroomRepo)(nil).Exists), ctx, roomID)
}

// MockslotRepo is a mock of slotRepo interface.
type MockslotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepoMockRecorder
}

// MockslotRepoMockRecorder is the mock recorder for MockslotRepo.
type MockslotRepoMockRecorder struct {
	mock *MockslotRepo
}

// NewMockslotRepo creates a new mock instance.
func NewMockslotRepo(ctrl *gomock.Controller) *MockslotRepo {
	mock := &MockslotRepo{ctrl: ctrl}
	mock.recorder = &MockslotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepo) EXPECT() *MockslotRepoMockRecorder {
	return m.recorder
}

// ListAvailableByRoomAndDate mocks base method.
func (m *MockslotRepo) ListAvailableByRoomAndDate(ctx context.Context, roomID uuid.UUID, date, now time.Time) ([]slot.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableByRoomAndDate", ctx, roomID, date, now)
	ret0, _ := ret[0].([]slot.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableByRoomAndDate indicates an expected call of ListAvailableByRoomAndDate.
func (mr *MockslotRepoMockRecorder) ListAvailableByRoomAndDate(ctx, roomID, date, now interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableByRoomAndDate", reflect.TypeOf((*MockslotRepo)(nil).ListAvailableByRoomAndDate), ctx, roomID, date, now)
}
