// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	schedule "github.com/internships-backend/test-backend-M0s1ck/internal/domain/schedule"
	slot "github.com/internships-backend/test-backend-M0s1ck/internal/domain/slot"
)

// MockscheduleRepo is a mock of scheduleRepo interface.
type MockscheduleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleRepoMockRecorder
}

// MockscheduleRepoMockRecorder is the mock recorder for MockscheduleRepo.
type MockscheduleRepoMockRecorder struct {
	mock *MockscheduleRepo
}

// NewMockscheduleRepo creates a new mock instance.
func NewMockscheduleRepo(ctrl *gomock.Controller) *MockscheduleRepo {
	mock := &MockscheduleRepo{ctrl: ctrl}
	mock.recorder = &MockscheduleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleRepo) EXPECT() *MockscheduleRepoMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockscheduleRepo) List(ctx context.Context) ([]schedule.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]schedule.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockscheduleRepoMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockscheduleRepo)(nil).List), ctx)
}

// MockslotRepo is a mock of slotRepo interface.
type MockslotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepoMockRecorder
}

// MockslotRepoMockRecorder is the mock recorder for MockslotRepo.
type MockslotRepoMockRecorder struct {
	mock *MockslotRepo
}

// NewMockslotRepo creates a new mock instance.
func NewMockslotRepo(ctrl *gomock.Controller) *MockslotRepo {
	mock := &MockslotRepo{ctrl: ctrl}
	mock.recorder = &MockslotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepo) EXPECT() *MockslotRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockslotRepo) Add(ctx context.Context, slots []slot.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockslotRepoMockRecorder) Add(ctx, slots interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockslotRepo)(nil).Add), ctx, slots)
}

// GetLastEndAtByRooms mocks base method.
func (m *MockslotRepo) GetLastEndAtByRooms(ctx context.Context, roomIDS []uuid.UUID) (map[uuid.UUID]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastEndAtByRooms", ctx, roomIDS)
	ret0, _ := ret[0].(map[uuid.UUID]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastEndAtByRooms indicates an expected call of GetLastEndAtByRooms.
func (mr *MockslotRepoMockRecorder) GetLastEndAtByRooms(ctx, roomIDS interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastEndAtByRooms", reflect.TypeOf((*MockslotRepo)(nil).GetLastEndAtByRooms), ctx, roomIDS)
}
