// Code generated by MockGen. DO NOT EDIT.
// Source: pass_comparor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockpassComparor is a mock of passComparor interface.
type MockpassComparor struct {
	ctrl     *gomock.Controller
	recorder *MockpassComparorMockRecorder
}

// MockpassComparorMockRecorder is the mock recorder for MockpassComparor.
type MockpassComparorMockRecorder struct {
	mock *MockpassComparor
}

// NewMockpassComparor creates a new mock instance.
func NewMockpassComparor(ctrl *gomock.Controller) *MockpassComparor {
	mock := &MockpassComparor{ctrl: ctrl}
	mock.recorder = &MockpassComparorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpassComparor) EXPECT() *MockpassComparorMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpassComparor) Compare(hash, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpassComparorMockRecorder) Compare(hash, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpassComparor)(nil).Compare), hash, password)
}
