// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	schedule "github.com/internships-backend/test-backend-M0s1ck/internal/domain/schedule"
	slot "github.com/internships-backend/test-backend-M0s1ck/internal/domain/slot"
)

// MockscheduleRepo is a mock of scheduleRepo interface.
type MockscheduleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockscheduleRepoMockRecorder
}

// MockscheduleRepoMockRecorder is the mock recorder for MockscheduleRepo.
type MockscheduleRepoMockRecorder struct {
	mock *MockscheduleRepo
}

// NewMockscheduleRepo creates a new mock instance.
func NewMockscheduleRepo(ctrl *gomock.Controller) *MockscheduleRepo {
	mock := &MockscheduleRepo{ctrl: ctrl}
	mock.recorder = &MockscheduleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockscheduleRepo) EXPECT() *MockscheduleRepoMockRecorder {
	return m.recorder
}

// GetByRoomID mocks base method.
func (m *MockscheduleRepo) GetByRoomID(ctx context.Context, roomID uuid.UUID) (*schedule.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoomID", ctx, roomID)
	ret0, _ := ret[0].(*schedule.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoomID indicates an expected call of GetByRoomID.
func (mr *MockscheduleRepoMockRecorder) GetByRoomID(ctx, roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoomID", reflect.TypeOf((*MockscheduleRepo)(nil).GetByRoomID), ctx, roomID)
}

// MockslotRepo is a mock of slotRepo interface.
type MockslotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockslotRepoMockRecorder
}

// MockslotRepoMockRecorder is the mock recorder for MockslotRepo.
type MockslotRepoMockRecorder struct {
	mock *MockslotRepo
}

// NewMockslotRepo creates a new mock instance.
func NewMockslotRepo(ctrl *gomock.Controller) *MockslotRepo {
	mock := &MockslotRepo{ctrl: ctrl}
	mock.recorder = &MockslotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslotRepo) EXPECT() *MockslotRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockslotRepo) Add(ctx context.Context, slots []slot.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockslotRepoMockRecorder) Add(ctx, slots interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockslotRepo)(nil).Add), ctx, slots)
}
