// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package create_test is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	room "github.com/internships-backend/test-backend-M0s1ck/internal/domain/room"
)

// MockroomRepo is a mock of roomRepo interface.
type MockroomRepo struct {
	ctrl     *gomock.Controller
	recorder *MockroomRepoMockRecorder
}

// MockroomRepoMockRecorder is the mock recorder for MockroomRepo.
type MockroomRepoMockRecorder struct {
	mock *MockroomRepo
}

// NewMockroomRepo creates a new mock instance.
func NewMockroomRepo(ctrl *gomock.Controller) *MockroomRepo {
	mock := &MockroomRepo{ctrl: ctrl}
	mock.recorder = &MockroomRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroomRepo) EXPECT() *MockroomRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockroomRepo) Create(ctx context.Context, room *room.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockroomRepoMockRecorder) Create(ctx, room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockroomRepo)(nil).Create), ctx, room)
}
